### ISSUE TITLE
linter-flow spawning 12 instances upon opening a project

### ISSUE THREAD

**Issue by gnestor** [AtomLinter/linter-flow#48] opened 2015-12-17 04:48 UTC
When I open a project when linter-flow is enabled, my CPU starts working really hard and when I check Activity Monitor, I see that there are 12 instances of flow running. Is this expected? How can I use Flow and/or linter-flow without burning up my CPU?

<img width="1280" alt="screen shot 2015-12-16 at 8 41 36 pm" src="https://cloud.githubusercontent.com/assets/512354/11861524/077b9eea-a436-11e5-8b02-e4504a1845bc.png">

**Comment by steelbrain** [comment] 2015-12-17 13:13
Dupe of #47

**Closed** 2015-12-17 17:37 UTC
