### ISSUE TITLE
flow methods cant resolve

### ISSUE THREAD

**Issue by sketchbuch** [AtomLinter/linter-flow#186] opened 2017-12-16 17:46 UTC
Atom marks my tests as containg errors. When I look at the files the only problems are that the flow methods can't be resolved. What causes this and how can I fix it?

I'm using create react app and have created a .eslintrc file as described on the CRA website.

**Comment by amercier** [comment] 2018-10-18 09:42
@sketchbuch If I understand correctly I'm having the same problem (sorry if it's not):

![image](https://user-images.githubusercontent.com/1246795/47145124-4dc7cf80-d2c9-11e8-8f7a-959fe9508d8b.png)

### Problem

1. Running `flow` passes => **OK**
2. Atom marks some methods as unknown (Cannot resolve method X) => **NOK**

### Cause

In my case, this is due to:
1. I'm using Jest (built in CRA),
2. I'm using [flow-typed](https://github.com/flow-typed/flow-typed) in order to load Jest type definitions,
3. I'm not checking the `flow-typed/` directory in my Git (added to `.gitignore`)

[linter-flow](https://github.com/AtomLinter/linter-flow/) seems to ignore library definitions when they are ignored in CVS.

@Arcanemagus Is this a bug or expected behavior?

### Solution

Checking the `flow-typed/` directory seems to solve the issue. This is the solution I have chosen. I think this is actually a good practice, since this prevents unpredictable build failure whenever a library definition is updated. This seems to be the [recommended way of using flow-typed](https://github.com/flow-typed/flow-typed#huh):

> All you have to do when you add one or more new dependencies to your project is run flow-typed install. This will search the libdef repo and download all the libdefs that are relevant for your project and install them for you. After that, simply check them in and be on your way!

**Comment by Arcanemagus** [comment] 2019-01-30 19:19
Closing based on the above.

**Closed by Arcanemagus** 2019-01-30 19:19 UTC
