### ISSUE TITLE
giant "merge_strict_job THROWS: ... Failure('hd')" error message about once a minute

### ISSUE THREAD

**Issue by AgentME** [AtomLinter/linter-flow#40] opened 2015-11-23 23:02 UTC
linter-flow had been working well for me, but then I decided to create a new file, and I started getting an error about once a minute from linter-flow. It doesn't let me copy the text from the error message, so here's a screenshot:

![screen shot 2015-11-23 at 2 58 51 pm](https://cloud.githubusercontent.com/assets/577345/11352704/be436816-91f2-11e5-987f-d03ba8f7527d.png)

Flow run from the command line reports "No errors!" so I can't see it being a problem with my code.

Closing the tab and restarting Atom doesn't fix it. The error message still mentions the same filename. I'm not sure why or how it's stuck on considering that file now.

**Comment by nmn** [comment] 2015-11-24 06:36
Atom version, OS info please.

Also please make sure:
1. restart atom and see if the problem persists
2. Open the dev tools (cmd+alt+i) and send a screenshot of the console
3. Provide any other steps involved to recreate the problem.

Thanks.

**Comment by AgentME** [comment] 2015-12-15 20:39
I had restarted several times and still had the issue. I stopped using linter-flow for a few weeks, but haven't seen the issue again since using it again. I'm on OS X.

**Comment by nmn** [comment] 2015-12-15 22:52
There were some bugs in Atom that have recently been fixed. May have been the root of the issue.

**Comment by nmn** [comment] 2015-12-18 22:52
Since you don't see this issue anymore, and I can't reproduce it, I'm closing this issue for now.

**Closed by nmn** 2015-12-18 22:52 UTC
