### ISSUE TITLE
Extremely dangerous behaviour on Windows

### ISSUE THREAD

**Issue by cristian-sima** [AtomLinter/linter-flow#130] opened 2016-08-16 09:39 UTC
```
Flow: v0.30.0
Windows 10 64bit
Atom: 1.9.8
```

Hi. I wanted to use the FlowJS on Atom. 

I installed it, and then .... wait ... and wait and nothing happened. 

I changed the path of flow to "W:/Developer/flow.exe". ----> Nothing.

I changed the path of flow to "W:\Developer\flow.exe". ----> Nothing.

And then, after 30 seconds, I realized  that my laptop is frozen. 😠 😠 💢 

With a great difficulty, I managed to see the Task Mananger and to see these astounding thing:

![image](https://cloud.githubusercontent.com/assets/12199042/17694599/493107c6-63ad-11e6-8223-1ec714c77150.png)

I closed Atom, stopped the `flow.exe processes` (it took 5 minutes) 💢  and then started again Atom. After 2 seconds:

![image](https://cloud.githubusercontent.com/assets/12199042/17694687/b1df44e0-63ad-11e6-92da-aefa1f5de953.png)

It is something going wrong with `linter-flow` on `Windows`. (I hope it is not something going wrong with `Windows` haha)

**Comment by cristian-sima** [comment] 2016-08-16 09:50
That's really curious. I've done a `flow --version` and I got this

![image](https://cloud.githubusercontent.com/assets/12199042/17695181/12908928-63b0-11e6-9c7d-19e40c767b6c.png)

**Comment by cristian-sima** [comment] 2016-08-16 09:57
I've changed to the last version. Installed the plugin again and again I have the CPU at `100%` without any result in Atom:

![image](https://cloud.githubusercontent.com/assets/12199042/17695377/f72cb23c-63b0-11e6-82b6-87c6195b7f9d.png)

**Comment by Arcanemagus** [comment] 2016-08-16 16:31
If I had to guess this is a duplicate of https://github.com/AtomLinter/linter-flow/issues/114, I didn't see that when working on the `flow@0.30.0` update though so I'm not sure what the problem might be...

**Closed** 2016-10-06 13:31 UTC
