### ISSUE TITLE
Doesn't work with flowtype v0.44

### ISSUE THREAD

**Issue by revyh** [AtomLinter/linter-flow#162] opened 2017-04-16 03:10 UTC
It looks like flow json output format has been modified and it doesn't contain `level` property anymore. So plugin [can't define error type](https://github.com/AtomLinter/linter-flow/blob/27a92820a37ddbdf42a25c94855dd4cd249b9e10/lib/message.js#L31)

I didn't track exact version in wich it happened, but plugin don't work for me at least with 0.44. Maybe related to https://github.com/AtomLinter/linter-flow/issues/158

**Comment by Arcanemagus** [comment] 2017-04-17 16:38
Duplicate of #160, unfortunately none of @AtomLinter/linter-flow seems to have taken that up yet.

**Closed by Arcanemagus** 2017-04-17 16:38 UTC

**Comment by KingScooty** [comment] 2017-04-19 16:08
@AtomLinter/linter-flow doesn't seem to be a real team? That page 404's.

**Comment by Arcanemagus** [comment] 2017-04-19 18:30
It is, unfortunately org teams aren't visible to non members. I'll see if I can devote some time to this later...
