### ISSUE TITLE
This is not working

### ISSUE THREAD

**Issue by Emilios1995** [AtomLinter/linter-flow#104] opened 2016-06-03 20:48 UTC
Sorry for not being more specific, butI don't know what's wrong.
I've set the correct flow path `/usr/local/bin/flow`, and when I run `/usr/local/bin/flow` or just `flow` in the console on the project folder it finds the errors in my code, but nothing is shown on the linter...
I'm using linter-eslint and that works properly.
Any idea?

**Comment by Arcanemagus** [comment] 2016-06-03 21:06
If you open Developer Tools and place a breakpoint [here](https://github.com/AtomLinter/linter-flow/blob/v5.4.0/lib/index.js#L61) is it ever triggered?

**Comment by Emilios1995** [comment] 2016-06-03 21:20
Yes, it is.
But I think I found a hint, when I run `flow` on the console, I see the following:
```
The flow server's version didn't match the client's, so it exited.
Going to launch a new one.

```

**Comment by nmn** [comment] 2016-06-03 23:20
@Emilios1995 I don't think that message will show up again. That only happens when you update flow.
Still I'm using the plugin on two macs. And a few friends at work are using it on macs as well. And I can't reproduce this bug anywhere. Are you sure you have the `@flow` comment? The plugin doesn't work without that.

**Comment by rgoldfinger** [comment] 2016-06-06 16:25
I'm having the same problem. Flow is returning the errors, but they are all filtered out by this line: https://github.com/AtomLinter/linter-flow/blob/v5.4.0/lib/message.js#L26

Removing this filter (by changing the line to `const blameMessages = flowMessages;`) surfaces some errors but causes other problems.

**Comment by nmn** [comment] 2016-06-08 02:50
@rgoldfinger that's a recent change. I'll take a look.

**Comment by rgoldfinger** [comment] 2016-06-09 15:33
I had a very old version of flow install (20). Everything works after upgrading to the latest version, sorry for the confusion.

**Comment by Arcanemagus** [comment] 2016-08-09 21:52
@Emilios1995 are you still having problems, or can this be closed?

**Comment by chrissm79** [comment] 2016-10-10 23:25
Having the same issue... I have Flow v0.33 installed in `/usr/local/bin/flow` which has been added to the settings but I don't see anything from the linter. If I run `/usr/local/bin/flow` in the command line it displays the errors in the project.

**Comment by Arcanemagus** [comment] 2019-01-30 18:50
Although _currently_ this doesn't appear to be working, I'm closing this issue as it seems what it was originally talking about was fixed.

**Closed by Arcanemagus** 2019-01-30 18:50 UTC
